name: lupus_app
description: Application dédiée aux patients lupiques pour les aider à organiser la prise de leurs médicaments et à suivre leurs symptômes.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+2

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^0.13.6
  convex_bottom_bar: ^3.2.0
  get: ^4.6.5
  intl: ^0.19.0
  image: ^4.0.17
  path_provider: ^2.0.15
  awesome_notifications: ^0.9.2
  reviews_slider: ^2.0.0
  awesome_dialog: ^3.0.2
  flutter_svg:
  syncfusion_flutter_charts: ^21.2.4
  webview_flutter_plus: ^0.3.0+2
  json_annotation: ^4.8.1
  permission_handler: ^10.4.3
  disable_battery_optimization: ^1.1.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/